### ISSUE TITLE
Not working with redis

### ISSUE THREAD

**Issue by Jack97** [spearmootz/node-laravel-session#1]
Everything works perfectly until I call getSessionFromRedis. 

My code:

```
laravelSession.getSessionFromRedis(sessionKey, redis).then((session) => {
    console.log('Session: ' + session);
});
```

**Session: undefined** is logged to the console.

**Comment by spearmootz** [comment]
@Jack97 thanks for the working feedback since its a new module.  when i made the redis functionality i did not have redis running on the environment but went off of old code i had written. i will test this today and fix this issue :)

**Comment by Jack97** [comment]
@spearmootz Thanks very much for the module, made my life a lot easier! :)

**Comment by Jack97** [comment]
If it helps at all, this is how I am currently getting the session from redis.

```
redis.get('laravel:' + sessionKey, function (err, reply) {
    session = unserialize(unserialize(reply));
    console.log(session);
});
```

**Comment by spearmootz** [comment]
yes it does...... it was a dumb mistake on my part. the callback i declared is (reply) instead of (err, reply).

i will commit and republish tonight, i will also notify you of the fix

**Comment by spearmootz** [comment]
@Jack97 one last time thank you.  not only was i not doing (err, value) but i was also expecting a promise instead of passing a callback. 

this issue is now closed

**Comment by Jack97** [comment]
No problem, glad I could help. Thanks again for the module :)
