### ISSUE TITLE
not support laravel 5.2

### ISSUE THREAD

**Issue by mvtcode** [spearmootz/node-laravel-session#2]
I using this module for laravel 5.2
**_Current cookie:_**
**laravel_session** = eyJpdiI6IkJpSUl2NDhPdkN0U1ZUMUJhVjFrd1E9PSIsInZhbHVlIjoidFFiYnppd3Y4ZDNyZjdNXC9RM1BoR0ZpblwvcG1kZlwvMVBWcnNNYUkwU1hKM2U0MEhwZms1WHNiQUlVNXBnWklrSWt3RHFXSU1ITHYrMzN6cjBsTFZobFE9PSIsIm1hYyI6ImJkZjFhZTRjNDQxNmVlNjA3YTE5YjE5ZWVhYTNhMTY1ZTc5MGU1NDFhMDY1ZmIzMzgzNmU1NGE2ZjM1MjUzNjIifQ==
**_My app config:_**
**Key_app** = LxLbNlIE6DJhAH8P6dgmcIaEt7Mkh... (32 characters)
But method: **laravelSession.getSessionKey(laravel_session,Key_app)** error:

> <error> SessionController.js:30 () Error: Invalid key length
>     at Error (native)
>     at new Decipheriv (crypto.js:235:16)
>     at Object.Decipheriv (crypto.js:232:12)
>     at Object.module.exports.getSessionKey (/home/tanmv/Dropbox/nodeapi/node_modules/node-laravel-session/index.js:37:30)
>     at /home/tanmv/Dropbox/nodeapi/http_controller/SessionController.js:26:35
>     at Layer.handle [as handle_request](/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/layer.js:95:5)
>     at next (/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/route.js:131:13)
>     at Route.dispatch (/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/route.js:112:3)
>     at Layer.handle [as handle_request](/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/layer.js:95:5)
>     at /home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/index.js:277:22
>     at Function.process_params (/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/index.js:330:12)
>     at next (/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/index.js:271:10)
>     at Function.handle (/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/index.js:176:3)
>     at router (/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/index.js:46:12)
>     at Layer.handle [as handle_request](/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/home/tanmv/Dropbox/nodeapi/node_modules/express/lib/router/index.js:312:13)

Help me, please!
Thank!

**Comment by spearmootz** [comment]
im pretty sure that i tested this with laravel 5.2 but i will test tonight or tomorrow and follow up.

**Comment by spearmootz** [comment]
but just wonderinf and to have information when i test. @mvtcode 

is it the default cipher ("AES-256-CBC") or did you change to another one? (found at config/app.php)
is your session being encrypted? (found at config/session.php) (if its not being encrypted then you do not need to use the getSessionKey method)

**Comment by mvtcode** [comment]
i using laravel 5.2 and config session redis.
config/session.php:

> 'driver' => env('SESSION_DRIVER', 'redis'),

I using **[laravel-session-parser](https://github.com/unknownuser88/laravel-session-parser)** module not fail. But using this module have this error.

**Comment by spearmootz** [comment]
I think the issue is you are using the encryption rijandel-128 vs the
default configuration.

**Comment by mvtcode** [comment]
I am not change file config/app.php, keep default:

> 'key' => env('APP_KEY'),
> 'cipher' => 'AES-256-CBC',

**Comment by spearmootz** [comment]
@mvtcode what node version are you using? 

right now i am testing on laravel 5.2.39, node V4.4.5 and i cannot seem to reproduce the error.

the laravel session looks correct, i passed it into the getSessionKey function and it passed the line where you are getting that error.   It messes up because i do not have the correct app key.
