### ISSUE TITLE
req is not defined

### ISSUE THREAD

**Issue by basherr** [spearmootz/node-laravel-session#4]
It would be really helpful If you could just add proper `example.js`. I didn't see any `req` as well from where actually it is coming.
```
let session = cookie.parse(req.headers.cookie).laravel_session;
                           ^
```

**Comment by spearmootz** [comment]
Thank you for the suggestion. Ill work on that today and hopefully get it out :)

**Comment by spearmootz** [comment]
@basherr i have added the example js you requested. let me know if it helps. I tried to comment everything.  if you feel its helpful but can be improved upon, please feel free to submit a pr :)
