### ISSUE TITLE
getUserIdFromSession(session) not working

### ISSUE THREAD

**Issue by charlesanthonyalfonso** [spearmootz/node-laravel-session#7]
Hi, my session payload has this attribute. `login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d`
so when i use the getUserIdFromSession method. it doesnt match the regex since you were not able to catch the succeeding _ after login_

`{ _token: '3YRd1Z3INEcKZsCS9iUoFvJ90waXt4vQWJheSuIq',
   _previous: { url: 'http://localhost:8000' },
  _flash: { old: {}, new: {} },
  login_web_59ba36addc2b2f9401580f014c7f58ea4e30989d: 3 }`

please do fix, thanks for the module by the way. its great.

**Comment by spearmootz** [comment]
is this a special configuration that cause it to have the login_web prefix? i havent been working with laravel recently (unfortunately) so im a bit rusty.

**Comment by charlesanthonyalfonso** [comment]
No, i am using laravel 5.5 with database as session driver

**Comment by spearmootz** [comment]
update to version 1.0.11 and it should work. let me know if the issue is not resolved

**Comment by spearmootz** [comment]
@charlesanthonyalfonso thanks for reporting this issue.

**Comment by charlesanthonyalfonso** [comment]
Hi, do you still need to update npm? 
because the latest version available in npm is still 1.0.10

**Comment by spearmootz** [comment]
try it now. i had published on my company's private npm. i have confirmer 1.0.11 is now available
