### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by gmatkowski** [spearmootz/node-laravel-session#9]
yntaxError: Unexpected token îŽ§ in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.getSessionKey (node-laravel-session/index.js:31:31)

**Comment by spearmootz** [comment]
Not enough details. If you don't mind sending me the cookie in text and laravel key with session config details I can't help with this.

**Comment by spearmootz** [comment]
I am closing this because you failed to follow up, i assume the error stopped appearing or you are using another solution
